name: "Build"

on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'
      - 'gradle/**'
      - 'plugins/**'
      - '**.gradle.kts'
      - '.github'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          ./gradlew make generateUpdaterJson
          cp ./plugins/kotlin/**/build/*.zip $GITHUB_WORKSPACE/builds
          cp build/updater.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --global pull.rebase true
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add *
          git commit -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push
